apiVersion: v1
kind: PersistentVolume
metadata:
  # name of mongo persistent volume
  name: mongo-pv-volume
spec:
  capacity:
    # set storage capacity 1 Gibibytes
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name of mongo persistent volume claim
  name: mongo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # set storage request 1 Gibibytes
      storage: 1Gi