version: "3.7"

services:

  order:

    # use image from ghcr.io/gesangwibawono1/order:latest
    image: ghcr.io/gesangwibawono1/order:latest

    # set policy restart to be always
    restart: always

    # mapping port 3000 container to port 3000 host
    ports:
      - 3000:3000

    # set environment for order container
    environment:
      # set environment for app port
      PORT: 3000
      # set environment for rabbit host
      AMQP_URL: amqp://rabbitmq:5672
    
    # wait from rabbitmq service
    depends_on:
      - rabbitmq

  shipping:

    # use image from ghcr.io/gesangwibawono1/shipping:latest
    image: ghcr.io/gesangwibawono1/shipping:latest

    # set policy restart to be always
    restart: always

    # mapping port 3000 container to port 3000 host
    ports:
      - 3001:3001

    # set environment for shipping container 
    environment:
      # set environment for app port
      PORT: 3001
      # set environment for rabbit host
      AMQP_URL: amqp://rabbitmq:5672
    
    # wait from rabbitmq service
    depends_on:
      - rabbitmq

  rabbitmq:

    image: rabbitmq:3.11-management

    # set policy restart to be always
    restart: always

    # mapping port 5672 container to port 5672 host and port 15672 container to port 15672 host
    ports:
      - 5672:5672
      - 15672:15672