version: "3.7"

services:

  item-app:

    # use image from gesangwibawono/item-app:1
    image: gesangwibawono/item-app:v1

    # set policy restart to be always
    restart: always

    # mapping port 8080 container to port 80 host
    ports:

      - 80:8080

    # wait from item-db service
    depends_on:
      - item-db

  item-db:

    # use image from mongo:3
    image: mongo:3

    # set volume mongo to app-db
    volumes:
      - app-db:/data/db 

volumes:

  # create volume
  app-db: