version: 2.1
orbs:
  go: circleci/go@1.7.3

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Lint Dockerfile"
          command: "docker run --rm --interactive hadolint/hadolint < Dockerfile"
  test-app:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - run:
          name: "Test app"
          command: "go test -v -short --count=1 $(go list ./...)"
  login-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Docker login"
          command: "echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin"
workflows:
  print-env-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - login-docker