version: 2.1

jobs:
  test-app:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Test app"
          command: "go test -v -short --count=1 $(go list ./...)"
  login-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Docker login"
          command: "echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin"
workflows:
  print-env-workflow:
    jobs:
      - test-app
      - login-docker