version: 2.1

jobs:
  print-env:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "My environment variables"
          command: "echo $DOCKERHUB_USERNAME $DOCKERHUB_PASSWORD"

workflows:
  print-env-workflow:
    jobs:
      - print-env