version: 2.1

jobs:
  print-env:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "My environment variables"
          command: "echo $DOCKERHUB_USERNAME $DOCKERHUB_PASSWORD"
  print-ls:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "My files"
          command: "ls -l"
  print-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Docker version"
          command: "docker --version"

workflows:
  print-env-workflow:
    jobs:
      - print-env
      - print-ls