apiVersion: apps/v1
kind: StatefulSet
metadata:
  # name of rabbitmq statefulset
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: broker
  # set service rabbitmq
  serviceName: rabbitmq
  # number replica 1
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: broker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      # pull image rabbitmq
      - image: rabbitmq
        name: rabbitmq:3.11-management
        ports:
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 15672
          name: rabbitmq-ui